_BASE_: ../../Base_R50_720p.yaml
MODEL:
  META_ARCHITECTURE: "pmt_online"
  BACKBONE:
    NAME: "PMT"
    NUM_BLOCKS: 6
    IMG_SIZE: 640
    NUM_CLASSES: 124
    HIDDEN_DIM: 1024
    SIZE_DIVISIBILITY: 32
    NUM_OBJECT_QUERIES: 200
    MASKED_ATTN_ENABLED: False
    DECODER_TYPE: "online"
    FROZEN_ENCODER: True  
    MODEL_NAME: "facebook/dinov3-vitl16-pretrain-lvd1689m"
    INTERACTION_INDICES: [5, 11, 17, 23]

    
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]


SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.0001
  LLRD: 0.6
  WEIGHT_DECAY: 0.05
  POLY_POWER: 0.9
  WARMUP_STEPS: 6000
  MAX_ITER: 40000

INPUT:
  SAMPLING_FRAME_NUM: 5
  SAMPLING_FRAME_RANGE: 2
  CROP:
    ENABLED: False
  PSEUDO:
    CROP:
      ENABLED: False


